#!/bin/bash
#
# Copyright (C) 2020 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Inputs:
# $1: Test's expected standard output
# $2: Test's actual standard output
# $3: Test's expected standard error
# $4: Test's actual standard error

# Check that one of the metrics appears in stderr.
grep 'Metrics reporting thread started' "$4" >/dev/null
THREAD_STARTED=$?

grep 'Timer expired, reporting metrics' "$4" >/dev/null
METRICS_REPORTED=$?

if [[ $THREAD_START -ne 0 ]] ; then
  # Print out the log and return with error.
  echo Metrics reporting thread did not start.
  cat "$4"
  exit 1
fi

if [[ $METRICS_REPORTED -ne 0 ]] ; then
  # Print out the log and return with error.
  echo Did not detect metrics report.
  cat "$4"
  exit 1
fi

# Success.
exit 0
